upstream bff {
    server bff-nodejs:3000;
}

server {
    listen 8080;

    # Rota principal: todo tráfego /api/ passa pelo BFF
    # O BFF agrega dados (GET /aggregated-data) e faz proxy CRUD de eventos e pedidos
    location /api/ {
        proxy_pass         http://bff;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   x-user-id         $http_x_user_id;
    }

    # Health check do gateway
    location /health {
        return 200 '{"status":"api-gateway ok"}';
        add_header Content-Type application/json;
    }
}
