@startuml UML-Components
title [UML Componentes] Plataforma de Tickets — Visão Geral

package "Frontend (React + Vite)" {
  [SPA Dashboard] as FE
}

package "BFF (NestJS :3000)" {
  [AggregatedDataController] as BFFC
  [AggregatedDataService] as BFFS
  BFFC --> BFFS : delega
}

package "MS Catálogo de Eventos\n(ASP.NET Core :5001)" {
  [EventosController] as EC
  [CreateEventoHandler] as CEH
  [GetEventoHandler] as GEH
  [GetAllEventosHandler] as GAEH
  [UpdateEventoHandler] as UEH
  [DeleteEventoHandler] as DEH
  [IEventoRepository] as IER
  [EventoRepository] as ER
  EC --> CEH
  EC --> GEH
  EC --> GAEH
  EC --> UEH
  EC --> DEH
  CEH --> IER
  GEH --> IER
  GAEH --> IER
  UEH --> IER
  DEH --> IER
  ER ..|> IER
}

package "MS Pedidos\n(ASP.NET Core :5002)" {
  [PedidosController] as PC
  [PedidoHandlers] as PH
  [IPedidoRepository] as IPR
  [PedidoRepository] as PR
  PC --> PH
  PH --> IPR
  PR ..|> IPR
}

package "Azure Function (:7071)" {
  [CalcularTaxaFunction] as AF
}

database "MongoDB\n:27017" as MONGO
database "SQL Server\n:1433" as SQL

FE --> BFFC : HTTP :3000
BFFS --> EC : HTTP :5001
BFFS --> PC : HTTP :5002
BFFS --> AF : HTTP :7071
ER --> MONGO : MongoDB Driver
PR --> SQL : EF Core
@enduml
