@startuml UML-Sequence
title [UML Sequência] Fluxo GET /aggregated-data — Plataforma de Tickets

actor "Usuário" as U
participant "React SPA\n:5173" as FE
participant "BFF NestJS\n:3000" as BFF
participant "MS Eventos\n(C# :5001)" as MSE
participant "MS Pedidos\n(C# :5002)" as MSP
participant "Azure Function\n(:7071)" as AF
database "MongoDB\n:27017" as MONGO
database "SQL Server\n:1433" as SQL

U -> FE: Acessa /dashboard
FE -> BFF: GET /api/aggregated-data\n[Header: x-user-id: kenji-dev]
activate BFF

par Promise.allSettled() — chamadas paralelas
  BFF -> MSE: GET /api/eventos
  MSE -> MONGO: db.eventos.find({})
  MONGO --> MSE: [Evento]
  MSE --> BFF: 200 JSON [Evento[]]
and
  BFF -> MSP: GET /api/pedidos
  MSP -> SQL: SELECT * FROM Pedidos
  SQL --> MSP: [Pedido]
  MSP --> BFF: 200 JSON [Pedido[]]
and
  BFF -> AF: GET /api/calcular-taxa\n?userId=kenji-dev&preco=450
  AF --> BFF: 200 JSON\n{ percentualAplicado, valorTaxa, mensagem }
end

deactivate BFF
BFF --> FE: 200 JSON\n{ usuarioId, taxaConvenienciaAtual,\n  eventosEmDestaque, meusUltimosPedidos }
FE --> U: Renderiza dashboard
@enduml
